### PR TITLE
Add option for dynamic channels

### LINKED ISSUE #13: Using 'this' in channel:'user.' + this.user.id
can I do something like this to apply current vue instance scope in channel: 'user.' + this.user.id 
```
channel: function (vm) {
return 'user.' + vm.user.id;
}
```

### PR DESCRIPTION
**Pull request by kamerat**
Fixes #13

* Added a way to add dynamic channels.
* Fixed better checks for correct channel input
* Moved beforeDestroy to mounted as a [programmatic listener](https://vuejs.org/v2/guide/components-edge-cases.html#Programmatic-Event-Listeners) to cut down on validation code
* Refactored some pre ES6 function declarations to arrow functions (there was a mix of both):
`function () {...}` -> `() => {...}`

### CODE REVIEW

**Comment by happyDemon** [comment]
thanks for the PR, I'll check things out when I get home and get a build ready

**Comment by kamerat** [comment]
Hey, @happyDemon! Sorry if I'm bothering you with this.
Do you have some time to spare to review the PR? :) 
Have a nice easter, my dude. 🐣

**Comment by wardy484** [comment]
😅  I was about to create a PR for this extact thing. 👍 Would be great if this was merged.

**Comment by kamerat** [comment]
Did you find the way home, @happyDemon? 😄 👉 ⌚

**Comment by kamerat** [comment]
Closing due to inactivity ⌚

**Pull request closed without merging**
